[2021-12-09 11:30:54,956] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2021-12-05T09:00:00+00:00 [queued]>
[2021-12-09 11:30:54,967] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2021-12-05T09:00:00+00:00 [queued]>
[2021-12-09 11:30:54,967] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-12-09 11:30:54,967] {taskinstance.py:881} INFO - Starting attempt 2 of 2
[2021-12-09 11:30:54,967] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-12-09 11:30:54,974] {taskinstance.py:901} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2021-12-05T09:00:00+00:00
[2021-12-09 11:30:54,976] {standard_task_runner.py:54} INFO - Started process 7702 to run task
[2021-12-09 11:30:55,029] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'twitter_dag', 'twitter_aluraonline', '2021-12-05T09:00:00+00:00', '--job_id', '26', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/twitter_dag.py', '--cfg_path', '/tmp/tmp5hb8vmen']
[2021-12-09 11:30:55,030] {standard_task_runner.py:78} INFO - Job 26: Subtask twitter_aluraonline
[2021-12-09 11:30:55,047] {logging_mixin.py:112} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2021-12-05T09:00:00+00:00 [running]> on host rafael-Aspire-A515-54G
[2021-12-09 11:30:55,088] {base_hook.py:89} INFO - Using connection to: id: twitter_default. Host: https://api.twitter.com, Port: None, Schema: None, Login: None, Password: None, extra: XXXXXXXX
[2021-12-09 11:30:55,090] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2021-12-05T09:00:00.00Z&end_time=2021-12-06T09:00:00.00Z
[2021-12-09 11:30:55,355] {logging_mixin.py:112} WARNING - /home/rafael/Documentos/alura/datapipeline/.env/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
[2021-12-09 11:30:55,833] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20211205T090000, start_date=20211209T143054, end_date=20211209T143055
[2021-12-09 11:30:59,944] {local_task_job.py:102} INFO - Task exited with return code 0
